name: build.yml

on:
  workflow_dispatch:
    branches: [ "master" ]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        cmake_preset: [
          msvc-release-x86,
          msvc-debug-x86,
          msvc-release-x64,
          msvc-debug-x64,
        ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ fromJSON('["x86", "x64"]')[contains(matrix.cmake_preset, 'x64')] }}

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - id: build_project
        name: Configure & Build
        run: |
          cmake . --preset ${{ matrix.cmake_preset }} -G Ninja
          cmake --build out/build/${{ matrix.cmake_preset }}

      - name: Run Tests
        if: ${{ steps.build_project.outcome == 'success' }}
        run: |
          cd src/test
          ../../out/build/${{matrix.cmake_preset}}/tm_parse_tests.exe